import os
import pandas as pd
import traceback
from app.core.openai_client import client, CHAT_MODEL
from app.core.logger import logger

UPLOADS_DIR = "uploads"  # Ensure this matches your actual folder path


def analyze_excel_intent(query: str) -> str:
    """
    Determines if the user wants to perform data analysis (Count, Sum, Avg)
    or just lookup a specific row/text.
    """
    system_prompt = (
        "You are a query router. Determine if the user's question requires "
        "analyzing the whole dataset (counting, summing, averaging, filtering multiple rows) "
        "or retrieving specific text details about a single entity."
        "\n\nExamples:"
        "\n- 'How many orders in 2023?' -> ANALYTIC"
        "\n- 'Total revenue from last month' -> ANALYTIC"
        "\n- 'What is the average price?' -> ANALYTIC"
        "\n- 'List all orders above $500' -> ANALYTIC"
        "\n- 'What is the address for user John?' -> LOOKUP"
        "\n- 'What is the status of order #123?' -> LOOKUP"
        "\n\nRespond ONLY with 'ANALYTIC' or 'LOOKUP'."
    )

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",  # Fast model is sufficient for routing
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": query},
            ],
            temperature=0,
        )
        return response.choices[0].message.content.strip().upper()
    except Exception as e:
        logger.error(f"Intent classification failed: {e}")
        return "LOOKUP"  # Default to standard RAG on error


def run_pandas_logic(file_name: str, query: str) -> str:
    """
    Loads the Excel file and executes Python code generated by LLM to answer the query.
    """
    file_path = os.path.join(UPLOADS_DIR, file_name)

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Excel file not found at: {file_path}")

    try:
        # 1. Load Data
        df = pd.read_excel(file_path)

        # Clean columns for easier LLM understanding
        df.columns = [str(col).strip() for col in df.columns]

        # 2. Prepare Context for LLM (Schema only, not data)
        schema_info = df.dtypes.to_string()
        columns_list = list(df.columns)

        prompt = f"""
        I have a pandas DataFrame `df` with the following columns: {columns_list}.
        Column Types:
        {schema_info}
        
        User Question: "{query}"
        
        Write valid Python code to calculate the answer.
        1. Store the final answer in a variable named `result`.
        2. If the answer is a number, ensure `result` is that number.
        3. If the answer is a list/dataframe, convert it to a string or list.
        4. Return ONLY the code. No markdown, no explanations.
        5. Use `df` directly.
        """

        # 3. Get Code
        response = client.chat.completions.create(
            model=CHAT_MODEL,  # Use GPT-4 class model for better coding
            messages=[
                {"role": "system", "content": "You are a Python data analyst."},
                {"role": "user", "content": prompt},
            ],
            temperature=0,
        )

        generated_code = response.choices[0].message.content
        # Clean code blocks if present
        generated_code = (
            generated_code.replace("```python", "").replace("```", "").strip()
        )

        logger.info(f"Pandas Generated Code: {generated_code}")

        # 4. Execute Code
        local_vars = {"df": df, "pd": pd}
        exec(generated_code, {}, local_vars)

        result = local_vars.get("result", "No result variable found.")

        # 5. Natural Language Wrapper
        # Convert the raw number/list back into a polite sentence
        final_prompt = f"The user asked: '{query}'. The calculated mathematical answer is: {result}. Formulate a concise sentence response."
        final_res = client.chat.completions.create(
            model="gpt-3.5-turbo", messages=[{"role": "user", "content": final_prompt}]
        )

        return final_res.choices[0].message.content

    except Exception as e:
        logger.error(f"Pandas execution error: {traceback.format_exc()}")
        return (
            f"I attempted to analyze the Excel file, but encountered an error: {str(e)}"
        )
